spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Para actualizar el schema automáticamente
spring.jpa.hibernate.ddl-auto=update

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Formatear las consultas SQL para que se vean bonitas
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
